### ISSUE TITLE
Where our website at dawgs

### ISSUE THREAD

**Issue by amroco** [SandDollarEnterprises/SandDollarEnterprises.github.io#1]

**Comment by angmelanie** [comment]
http://sanddollarenterprises.com/ @amroco @Gtsui091

**Comment by gtsui091** [comment]
looks like a quality site already

**Comment by gtsui091** [comment]
Do you guys want to pick a theme to use?
http://themes.jekyllrc.org/

**Comment by angmelanie** [comment]
I thought you or Eric were gonna design it from scratch

**Comment by ericjsy** [comment]
It was me or the theme. I lost.

**Comment by angmelanie** [comment]
We regret to inform you that the Sand Dollar CEOs made an executive decision that we couldn't trust you enough to give you access to our exclusive github page. Please apply again.
